/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'cat' at '3/13/17 4:37 PM' with Gradle 3.1
 *
 * @author cat, @date 3/13/17 4:37 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
